import { useState, useMemo, useCallback } from 'react';
import { AI_TOOLS } from '../data/aiTools';
import AdSlot from '../components/AdSlot';
import { AD_SLOTS } from '../lib/adsense';
import { useDocumentMeta } from '../lib/useDocumentMeta';
import {
  humanize, detectAI, tokenStats, buildPrompt, summarize,
  PROMPT_FORMATS, PROMPT_TONES, PROMPT_PRESETS,
} from '../lib/aiToolkit';

/* ----------------------------- icons ----------------------------- */
const CopyIcon = () => (
  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
  </svg>
);
const CheckIcon = () => (
  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
);

/* ---------------------- small shared widgets --------------------- */
function CopyButton({ text, label = 'Copy' }) {
  const [done, setDone] = useState(false);
  const onCopy = async () => {
    if (!text) return;
    try { await navigator.clipboard.writeText(text); } catch { /* clipboard blocked */ }
    setDone(true);
    setTimeout(() => setDone(false), 1600);
  };
  return (
    <button className="tool-copy-btn" onClick={onCopy} disabled={!text}>
      {done ? <CheckIcon /> : <CopyIcon />} {done ? 'Copied!' : label}
    </button>
  );
}

const wc = (s) => (s.trim().match(/[A-Za-z0-9'’-]+/g) || []).length;

/* ============================ TOOL 1 ============================= */
function HumanizerTool() {
  const [input, setInput] = useState('');
  const [contractions, setContractions] = useState(true);
  const result = useMemo(() => humanize(input, { contractions }), [input, contractions]);
  return (
    <div className="tool-grid">
      <div className="tool-pane">
        <div className="tool-pane-head">
          <span className="tool-pane-label">Your AI text</span>
          <span className="tool-meta">{wc(input)} words</span>
        </div>
        <textarea
          className="tool-textarea"
          placeholder="Paste text generated by ChatGPT, Claude or Gemini…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <label className="tool-check">
          <input type="checkbox" checked={contractions} onChange={(e) => setContractions(e.target.checked)} />
          Add natural contractions (it's, don't, you're…)
        </label>
      </div>
      <div className="tool-pane">
        <div className="tool-pane-head">
          <span className="tool-pane-label">Humanized result</span>
          {result.changes > 0 && <span className="tool-badge-pill">{result.changes} edits</span>}
        </div>
        <div className="tool-output" aria-live="polite">
          {result.text || <span className="tool-placeholder">Your rewritten text appears here…</span>}
        </div>
        <div className="tool-actions">
          <CopyButton text={result.text} label="Copy result" />
        </div>
      </div>
    </div>
  );
}

/* ============================ TOOL 2 ============================= */
function gaugeColor(score) {
  if (score >= 70) return '#EF4444';
  if (score >= 50) return '#F59E0B';
  if (score >= 32) return '#EAB308';
  return '#10B981';
}
function DetectorTool() {
  const [input, setInput] = useState('');
  const res = useMemo(() => detectAI(input), [input]);
  return (
    <div className="tool-grid">
      <div className="tool-pane">
        <div className="tool-pane-head">
          <span className="tool-pane-label">Text to analyze</span>
          <span className="tool-meta">{res.wordCount} words</span>
        </div>
        <textarea
          className="tool-textarea"
          placeholder="Paste any text — an essay, article or message — to check how AI-like it reads (min. 25 words)…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
      </div>
      <div className="tool-pane">
        <div className="tool-pane-head"><span className="tool-pane-label">Result</span></div>
        {res.score === null ? (
          <div className="tool-output"><span className="tool-placeholder">Add at least 25 words to run the detector…</span></div>
        ) : (
          <div className="detector-result">
            <div className="detector-gauge" style={{ '--g': gaugeColor(res.score) }}>
              <div className="detector-gauge-num">{res.score}<span>%</span></div>
              <div className="detector-gauge-label">AI likelihood</div>
            </div>
            <div className="detector-verdict" style={{ color: gaugeColor(res.score) }}>{res.verdict}</div>
            <div className="detector-factors">
              {res.factors.map((f) => (
                <div className="detector-factor" key={f.label}>
                  <div className="detector-factor-top">
                    <span>{f.label}</span><span className="detector-factor-score">{f.score}</span>
                  </div>
                  <div className="detector-bar"><div className="detector-bar-fill" style={{ width: `${f.score}%`, background: gaugeColor(res.score) }} /></div>
                  <div className="detector-factor-detail">{f.detail}</div>
                </div>
              ))}
            </div>
            <p className="tool-note">Heuristic estimate based on writing-style signals — use it as a guide, not proof.</p>
          </div>
        )}
      </div>
    </div>
  );
}

/* ============================ TOOL 3 ============================= */
function TokenTool() {
  const [input, setInput] = useState('');
  const s = useMemo(() => tokenStats(input), [input]);
  const fmt = (n) => n < 0.01 ? `$${n.toFixed(5)}` : `$${n.toFixed(4)}`;
  return (
    <div className="tool-grid">
      <div className="tool-pane">
        <div className="tool-pane-head"><span className="tool-pane-label">Your prompt / text</span></div>
        <textarea
          className="tool-textarea"
          placeholder="Paste a prompt or document to estimate tokens and API cost…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <div className="token-stats">
          <div className="token-stat"><b>{s.tokens.toLocaleString()}</b><span>tokens*</span></div>
          <div className="token-stat"><b>{s.words.toLocaleString()}</b><span>words</span></div>
          <div className="token-stat"><b>{s.chars.toLocaleString()}</b><span>characters</span></div>
          <div className="token-stat"><b>{s.sentences.toLocaleString()}</b><span>sentences</span></div>
        </div>
      </div>
      <div className="tool-pane">
        <div className="tool-pane-head"><span className="tool-pane-label">Estimated cost per call</span></div>
        <div className="token-table">
          <div className="token-row token-row-head">
            <span>Model</span><span>Ctx</span><span>Input</span><span>In + out</span>
          </div>
          {s.costs.map((m) => (
            <div className="token-row" key={m.id}>
              <span className="token-model">{m.name}</span>
              <span className="token-ctx">{m.ctx}</span>
              <span>{fmt(m.inCost)}</span>
              <span className="token-rt">{fmt(m.roundTrip)}</span>
            </div>
          ))}
        </div>
        <p className="tool-note">*Token count is a fast local estimate (±10–15%). Prices are illustrative public list rates and change over time.</p>
      </div>
    </div>
  );
}

/* ============================ TOOL 4 ============================= */
function PromptTool() {
  const [f, setF] = useState({
    role: '', task: '', audience: '', context: '',
    format: PROMPT_FORMATS[0], tone: PROMPT_TONES[0], constraints: '',
  });
  const set = (k) => (e) => setF((p) => ({ ...p, [k]: e.target.value }));
  const applyPreset = useCallback((p) => {
    setF((prev) => ({ ...prev, role: p.role, task: p.task, audience: p.audience, format: p.format, tone: p.tone }));
  }, []);
  const prompt = useMemo(() => buildPrompt(f), [f]);
  return (
    <div className="tool-grid">
      <div className="tool-pane">
        <div className="tool-pane-head"><span className="tool-pane-label">Build your prompt</span></div>
        <div className="prompt-presets">
          {PROMPT_PRESETS.map((p) => (
            <button key={p.label} className="prompt-preset" onClick={() => applyPreset(p)}>{p.label}</button>
          ))}
        </div>
        <label className="tool-field"><span>AI should act as…</span>
          <input className="tool-input" placeholder="an expert content writer" value={f.role} onChange={set('role')} />
        </label>
        <label className="tool-field"><span>Task</span>
          <input className="tool-input" placeholder="Write a 1,200-word blog post about remote work" value={f.task} onChange={set('task')} />
        </label>
        <label className="tool-field"><span>Audience (optional)</span>
          <input className="tool-input" placeholder="people new to the subject" value={f.audience} onChange={set('audience')} />
        </label>
        <label className="tool-field"><span>Context / details (optional)</span>
          <textarea className="tool-input tool-input-area" placeholder="Key facts, links, or constraints the AI should use…" value={f.context} onChange={set('context')} />
        </label>
        <div className="tool-field-row">
          <label className="tool-field"><span>Format</span>
            <select className="tool-input" value={f.format} onChange={set('format')}>
              {PROMPT_FORMATS.map((o) => <option key={o}>{o}</option>)}
            </select>
          </label>
          <label className="tool-field"><span>Tone</span>
            <select className="tool-input" value={f.tone} onChange={set('tone')}>
              {PROMPT_TONES.map((o) => <option key={o}>{o}</option>)}
            </select>
          </label>
        </div>
      </div>
      <div className="tool-pane">
        <div className="tool-pane-head"><span className="tool-pane-label">Your ready-to-paste prompt</span></div>
        <div className="tool-output tool-output-mono" aria-live="polite">
          {f.task || f.role ? prompt : <span className="tool-placeholder">Fill in a task and your prompt appears here…</span>}
        </div>
        <div className="tool-actions">
          <CopyButton text={f.task || f.role ? prompt : ''} label="Copy prompt" />
          <a className="tool-launch" href={`https://chatgpt.com/?q=${encodeURIComponent(prompt)}`} target="_blank" rel="noopener noreferrer">Open in ChatGPT →</a>
        </div>
      </div>
    </div>
  );
}

/* ============================ TOOL 5 ============================= */
const LENGTHS = [
  { label: 'Short', ratio: 0.18 },
  { label: 'Medium', ratio: 0.32 },
  { label: 'Long', ratio: 0.5 },
];
function SummarizerTool() {
  const [input, setInput] = useState('');
  const [li, setLi] = useState(1);
  const res = useMemo(() => summarize(input, LENGTHS[li].ratio), [input, li]);
  return (
    <div className="tool-grid">
      <div className="tool-pane">
        <div className="tool-pane-head">
          <span className="tool-pane-label">Text to summarize</span>
          <span className="tool-meta">{wc(input)} words</span>
        </div>
        <textarea
          className="tool-textarea"
          placeholder="Paste an article, essay or report to condense into its key sentences…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <div className="seg-control">
          {LENGTHS.map((l, i) => (
            <button key={l.label} className={`seg-btn${i === li ? ' active' : ''}`} onClick={() => setLi(i)}>{l.label}</button>
          ))}
        </div>
      </div>
      <div className="tool-pane">
        <div className="tool-pane-head">
          <span className="tool-pane-label">Summary</span>
          {res.summary && <span className="tool-badge-pill">{res.kept}/{res.total} sentences</span>}
        </div>
        <div className="tool-output" aria-live="polite">
          {res.summary || <span className="tool-placeholder">Your summary appears here…</span>}
        </div>
        <div className="tool-actions"><CopyButton text={res.summary} label="Copy summary" /></div>
      </div>
    </div>
  );
}

/* --------------------------- tool map ---------------------------- */
const TOOL_UI = {
  humanizer: HumanizerTool,
  detector: DetectorTool,
  tokens: TokenTool,
  prompt: PromptTool,
  summarizer: SummarizerTool,
};

/* ============================ PAGE =============================== */
export default function AIToolsPage() {
  useDocumentMeta({
    title: 'Free AI Tools — Humanizer, AI Detector, Token Counter & More',
    description:
      'Free, no-signup AI tools that run in your browser: AI text humanizer, AI content detector, token & cost counter, prompt generator and text summarizer. Instant results, no limits.',
    path: '/ai-tools',
  });

  const [active, setActive] = useState(AI_TOOLS[0].id);
  const tool = AI_TOOLS.find((t) => t.id === active) || AI_TOOLS[0];
  const ActiveUI = TOOL_UI[tool.id];

  return (
    <div className="page-section">
      <div className="container">
        <div className="page-hero" style={{ paddingTop: 'calc(var(--navbar-h) + 56px)', paddingBottom: 22, textAlign: 'center' }}>
          <p className="section-label" style={{ marginBottom: 12 }}>Free · No signup · Runs in your browser</p>
          <h1 className="page-hero-title">Free <span className="grad-text">AI Tools</span></h1>
          <p className="hero-sub" style={{ margin: '0 auto 8px' }}>
            {AI_TOOLS.length} genuinely useful AI tools you can use right now — nothing to install,
            no account, no word limits. Pick a tool and get an instant result.
          </p>
        </div>

        <p className="tools-disclaimer">
          These tools run heuristics and estimates in your browser and are provided for general
          guidance only — results may be inaccurate. In particular, the <strong>AI Detector</strong> gives a
          probabilistic estimate, not proof, and should never be used to make consequential decisions
          about a person (e.g. academic or hiring penalties). See our <a href="/terms">Terms of Use</a>.
        </p>

        <AdSlot slot={AD_SLOTS.toolsTop} className="ad-leaderboard" />

        {/* Tool picker cards */}
        <div className="tool-cards" role="tablist" aria-label="Free AI tools">
          {AI_TOOLS.map((t) => (
            <button
              key={t.id}
              role="tab"
              aria-selected={t.id === active}
              className={`tool-card${t.id === active ? ' active' : ''}`}
              onClick={() => setActive(t.id)}
              style={{ '--tc': t.color }}
            >
              <span className="tool-card-badge" style={{ background: t.color }}>{t.badge}</span>
              <span className="tool-card-text">
                <span className="tool-card-name">{t.name}</span>
                <span className="tool-card-tag">{t.tagline}</span>
              </span>
            </button>
          ))}
        </div>

        {/* Active tool workspace */}
        <section className="tool-workspace glass" key={tool.id} style={{ '--tc': tool.color }}>
          <div className="tool-workspace-head">
            <span className="tool-card-badge lg" style={{ background: tool.color }}>{tool.badge}</span>
            <div>
              <h2 className="tool-workspace-title">{tool.name}</h2>
              <p className="tool-workspace-blurb">{tool.blurb}</p>
            </div>
          </div>
          <ActiveUI />
        </section>

        <AdSlot slot={AD_SLOTS.toolsInline} className="ad-inline" />

        {/* SEO / value copy — also helps the page rank for each tool's queries */}
        <section className="tool-seo">
          {AI_TOOLS.map((t) => (
            <div className="tool-seo-item" key={t.id}>
              <h3>{t.name}</h3>
              <p>{t.blurb}</p>
              <p className="tool-seo-kw">Popular searches: {t.keywords.join(' · ')}</p>
            </div>
          ))}
        </section>

        <div className="section-site-link" style={{ marginBottom: 60 }}>
          More AI news, tools &amp; insights at{' '}
          <a href="https://glancerai.com" target="_blank" rel="noopener noreferrer">glancerai.com</a>
        </div>
      </div>
    </div>
  );
}
